package com.example.thibault.feedme.Persistence;

import com.j256.ormlite.field.DatabaseField;

/**
 * Created by Thibault on 20/09/2015.
 */
public class Adresse {


    // id is generated by the database and set on the object automagically
    @DatabaseField(generatedId = true)
    long id;
    @DatabaseField(canBeNull = false)
    String voie;
    @DatabaseField(foreign = true)
    Ville ville;


    Adresse() {
        // needed by ormlite
    }

    public Adresse(String voie, Ville ville) {

        this.voie = voie;
        this.ville = ville;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("id=").append(this.id);
        sb.append(", ").append("voie : ").append(this.voie);
        sb.append(", ").append("ville : ").append(this.ville.toString());

        return sb.toString();
    }

    public long getId() {
        return id;
    }

    public String getVoie() {
        return voie;
    }

    public Ville getVille() {
        return ville;
    }
}
