package com.example.thibault.feedme.Persistence;

import com.j256.ormlite.field.DatabaseField;

/**
 * Created by Thibault on 25/09/2015.
 */
public class Authentification {

    // id is generated by the database and set on the object automagically
    @DatabaseField
    String password;
    @DatabaseField(foreign = true)
    long idRole;
    @DatabaseField(foreign = true)
    long idUser;


    Authentification() {
        // needed by ormlite
    }

    public Authentification(String password, long idRole, long idUser) {

        this.password = password;
        this.idRole = idRole;
        this.idUser = idUser;

    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Password : ").append("*********");
        sb.append(", ").append("id Role : ").append(this.idRole);
        sb.append(", ").append("id Utilisateur : ").append(this.idUser);

        return sb.toString();
    }
}
