package com.example.thibault.feedme.Persistence;

import com.j256.ormlite.field.DatabaseField;

import java.sql.Time;
import java.sql.Timestamp;
import java.util.Date;

/**
 * Created by Thibault on 19/09/2015.
 */
public class Offre {

    // id is generated by the database and set on the object automagically
    @DatabaseField(generatedId = true)
    long id;
    @DatabaseField(canBeNull = false)
    Date dateCreation;
    @DatabaseField(canBeNull = false)
    String titre;
    @DatabaseField(canBeNull = false)
    Integer prix;
    @DatabaseField(canBeNull = false)
    Integer nbPrsn;
    @DatabaseField(canBeNull = false)
    Integer durée;
    @DatabaseField(canBeNull = false)
    Date dateRepas;
    @DatabaseField(foreign = true, canBeNull = false, foreignAutoRefresh = true, foreignAutoCreate = true, maxForeignAutoRefreshLevel=3)
    Adresse idAdress;
    @DatabaseField
    String notes;
    @DatabaseField(canBeNull = false)
    String menu;
    @DatabaseField
    Integer  ageMin;
    @DatabaseField
    Integer ageMax;
    @DatabaseField(canBeNull = false)
    boolean animaux;
    @DatabaseField(foreign = true, foreignAutoRefresh = true,canBeNull = false, foreignAutoCreate = true)
    TypeCuisine typeCuisine;
    @DatabaseField(foreign = true, foreignAutoRefresh = true,canBeNull = false, foreignAutoCreate = true)
    User idUser;





    Offre() {
        // needed by ormlite
    }

    public Offre(Date dateCreation, String titre, Integer prix,Integer nbPrsn,Integer durée, Date dateRepas, Adresse idAdress, String notes, String menu,Integer ageMin, Integer ageMax,boolean animaux, TypeCuisine typeCuisine, User idUser) {

        this.dateCreation =dateCreation;
        this.titre=titre;
        this.prix=prix;
        this.nbPrsn=nbPrsn;
        this.durée = durée;
        this.dateRepas=dateRepas;
        this.idAdress=idAdress;
        this.notes=notes;
        this.menu=menu;
        this.ageMin=ageMin;
        this.ageMax=ageMax;
        this.animaux=animaux;
        this.typeCuisine=typeCuisine;
        this.idUser=idUser;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("id=").append(this.id);
        sb.append(", ").append("date de création : ").append(this.dateCreation);
        sb.append(", ").append("titre : ").append(this.titre);
        sb.append(", ").append("prix : ").append(this.prix);
        sb.append(", ").append("nombre de persone : ").append(this.nbPrsn);
        sb.append(", ").append("durée : ").append(this.durée);
        sb.append(", ").append("dateRepas : ").append(this.dateRepas);
        sb.append(", ").append("id d'adresse : ").append(this.idAdress.toString());
        sb.append(", ").append("notes : ").append(this.notes);
        sb.append(", ").append("menu : ").append(this.menu);
        sb.append(", ").append("age minimum : ").append(this.ageMin);
        sb.append(", ").append("age maximum : ").append(this.ageMax);
        sb.append(", ").append("Type de cuisine").append(this.typeCuisine.toString());
        sb.append(", ").append("Initiateur").append(this.idUser.toString());
        return sb.toString();
    }

    public long getId() {
        return id;
    }

    public TypeCuisine getTypeCuisine() {
        return typeCuisine;
    }

    public User getIdUser() {
        return idUser;
    }

    public boolean isAnimaux() {
        return animaux;
    }

    public Integer getAgeMax() {
        return ageMax;
    }

    public Integer getAgeMin() {
        return ageMin;
    }

    public String getMenu() {
        return menu;
    }

    public String getNotes() {
        return notes;
    }

    public Adresse getIdAdress() {
        return idAdress;
    }

    public Date getDateRepas() {
        return dateRepas;
    }

    public Integer getDurée() {
        return durée;
    }

    public Integer getNbPrsn() {
        return nbPrsn;
    }

    public Integer getPrix() {
        return prix;
    }

    public Date getDateCreation() {
        return dateCreation;
    }

    public String getTitre() {
        return titre;
    }
}

