package com.example.thibault.feedme.Persistence;

import com.j256.ormlite.field.DatabaseField;

import java.sql.Time;
import java.sql.Timestamp;
import java.util.Date;

/**
 * Created by Thibault on 19/09/2015.
 */
public class Offre {

    // id is generated by the database and set on the object automagically
    @DatabaseField(generatedId = true)
    long id;
    @DatabaseField
    Date dateCreation;
    @DatabaseField
    String titre;
    @DatabaseField
    Integer prix;
    @DatabaseField
    Integer nbPrsn;
    @DatabaseField
    Time durée;
    @DatabaseField
    Timestamp dateRepas;
    @DatabaseField(foreign = true)
    Integer idAdress;
    @DatabaseField
    String notes;
    @DatabaseField
    String menu;
    @DatabaseField
    Integer  ageMin;
    @DatabaseField
    Integer ageMax;
    @DatabaseField
    boolean animaux;
    @DatabaseField(foreign = true)
    long typeCuisine;
    @DatabaseField(foreign = true)
    long idUser;





    Offre() {
        // needed by ormlite
    }

    public Offre(Date dateCreation, String titre, Integer prix,Integer nbPrsn,Time durée, Timestamp dateRepas, Integer idAdress, String notes, String menu,Integer ageMin, Integer ageMax,boolean animaux, long typeCuisine, long idUser) {

        this.dateCreation =dateCreation;
        this.titre=titre;
        this.prix=prix;
        this.nbPrsn=nbPrsn;
        this.durée = durée;
        this.dateRepas=dateRepas;
        this.idAdress=idAdress;
        this.notes=notes;
        this.menu=menu;
        this.ageMin=ageMin;
        this.ageMax=ageMax;
        this.animaux=animaux;
        this.typeCuisine=typeCuisine;
        this.idUser=idUser;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("id=").append(this.id);
        sb.append(", ").append("date de création : ").append(this.dateCreation);
        sb.append(", ").append("titre : ").append(this.titre);
        sb.append(", ").append("prix : ").append(this.prix);
        sb.append(", ").append("nombre de persone : ").append(this.nbPrsn);
        sb.append(", ").append("durée : ").append(this.durée);
        sb.append(", ").append("dateRepas : ").append(this.dateRepas);
        sb.append(", ").append("id d'adresse : ").append(this.idAdress);
        sb.append(", ").append("notes : ").append(this.notes);
        sb.append(", ").append("menu : ").append(this.menu);
        sb.append(", ").append("age minimum : ").append(this.ageMin);
        sb.append(", ").append("age maximum : ").append(this.ageMax);
        sb.append(", ").append("Type de cuisine").append(this.typeCuisine);
        sb.append(", ").append("Initiateur").append(this.idUser);
        return sb.toString();
    }
}

