package com.example.thibault.feedme.Persistence;

import com.j256.ormlite.field.DatabaseField;

import java.util.Date;

/**
 * Created by Thibault on 19/09/2015.
 */
public class Particulier {


    // id is generated by the database and set on the object automagically
    @DatabaseField(generatedId = true)
    int id;
    @DatabaseField
    String prenom;
    @DatabaseField
    Date dateNaissance;



    Particulier() {
        // needed by ormlite
    }

    Particulier(String prenom, Date dateNaissance){

        this.prenom=prenom;
        this.dateNaissance=dateNaissance;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("id=").append(this.id);
        sb.append(", ").append("Prénom : ").append(this.prenom);
        sb.append(", ").append("date de naissance : ").append(this.dateNaissance);

        return sb.toString();
    }
}
