package com.example.thibault.feedme.Persistence;

import com.j256.ormlite.field.DatabaseField;

/**
 * Created by Thibault on 20/09/2015.
 */
public class Pays {

    // id is generated by the database and set on the object automagically
    @DatabaseField(generatedId = true)
    int id;
    @DatabaseField
    String code;
    @DatabaseField
    String nom;


    Pays() {
        // needed by ormlite
    }

    public Pays(String code, String nom) {

        this.code = code;
        this.nom = nom;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("id=").append(this.id);
        sb.append(", ").append("code : ").append(this.code);
        sb.append(", ").append("nom : ").append(this.nom);

        return sb.toString();
    }
}
