package com.example.thibault.feedme.Persistence;

import com.j256.ormlite.field.DatabaseField;

import java.sql.Timestamp;

/**
 * Created by Thibault on 19/09/2015.
 */
public class Reservation {
    // id is generated by the database and set on the object automagically
    @DatabaseField(foreign = true, id = true)
    int offreId;
    @DatabaseField(foreign = true, id = true)
    int hoteId;
    @DatabaseField(foreign = true, id = true)
    int conId;
    @DatabaseField
    String etat;
    @DatabaseField
    Timestamp date;


    Reservation() {
        // needed by ormlite
    }

    Reservation(int offreId, int hoteId,int conId, String etat, Timestamp date) {

        this.offreId = offreId;
        this.hoteId=hoteId;
        this.conId=conId;
        this.etat=etat;
        this.date=date;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("offre ID = ").append(this.offreId);
        sb.append(", ").append("hote ID : ").append(this.hoteId);
        sb.append(", ").append("con ID : ").append(this.conId);
        sb.append(", ").append("etat : ").append(this.etat);
        sb.append(", ").append("date : ").append(this.date);

        return sb.toString();
    }
}
