package com.example.thibault.feedme.Persistence;

import com.j256.ormlite.field.DatabaseField;

import java.sql.Timestamp;
import java.util.Date;

/**
 * Created by Thibault on 19/09/2015.
 */
public class Reservation {
    // id is generated by the database and set on the object automagically
    @DatabaseField(generatedId = true)
    long id;
    @DatabaseField(foreign = true, foreignAutoRefresh = true, foreignAutoCreate = true, canBeNull = false)
    Offre offreId;
    @DatabaseField(foreign = true, foreignAutoRefresh = true, foreignAutoCreate = true, canBeNull = false)
    User conId;
    /**
     * @DatabaseField(canBeNull = false)
     * String etat;
     */
    @DatabaseField(canBeNull = false)
    Date date;


    Reservation() {
        // needed by ormlite
    }

    public Reservation(Offre offreId, User conId, Date date) {

        this.offreId = offreId;
        this.conId = conId;
        this.date = date;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Id=").append(this.id);
        sb.append(", ").append("offre ID = ").append(this.offreId);
        sb.append(", ").append("con ID : ").append(this.conId);
        sb.append(", ").append("date : ").append(this.date);

        return sb.toString();
    }

    public Offre getOffreId() {
        return offreId;
    }

    public long getId() {
        return id;
    }

    public User getConId() {
        return conId;
    }

    public Date getDate() {
        return date;
    }
}
