package com.example.thibault.feedme.Persistence;

import com.j256.ormlite.field.DatabaseField;

import java.util.Date;

/**
 * Created by Thibault on 19/09/2015.
 */
public class TypeCuisine {


    // id is generated by the database and set on the object automagically
    @DatabaseField(generatedId = true)
    int id;
    @DatabaseField
    String typeCuisine;




    TypeCuisine() {
        // needed by ormlite
    }

    TypeCuisine(String typeCuisine){

        this.typeCuisine=typeCuisine;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("id=").append(this.id);
        sb.append(", ").append("Type de cuisine : ").append(this.typeCuisine);


        return sb.toString();
    }
}
