package com.example.thibault.feedme.Persistence;

import com.j256.ormlite.field.DatabaseField;

import java.util.Date;

/**
 * Created by Thibault on 19/09/2015.
 */
public class User {

    // id is generated by the database and set on the object automagically
    @DatabaseField(generatedId = true)
    int id;
    @DatabaseField
    String nom;
    @DatabaseField
    String password;
    @DatabaseField
    String email;


    User() {
        // needed by ormlite
    }

    User(String nom, String password, String email){

        this.nom =nom;
        this.password=password;
        this.email=email;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("id=").append(this.id);
        sb.append(", ").append("Nom : ").append(this.nom);
        sb.append(", ").append("password : ").append("*******");
        sb.append(", ").append("email : ").append(this.email);

        return sb.toString();
    }

}
