package com.example.thibault.feedme.Persistence;

import com.j256.ormlite.field.DatabaseField;

/**
 * Created by Thibault on 20/09/2015.
 */
public class Ville {
    // id is generated by the database and set on the object automagically
    @DatabaseField(generatedId = true)
    long id;
    @DatabaseField
    String nom;
    @DatabaseField
    String codePostal;
    @DatabaseField(foreign = true)
    long pays;


    Ville() {
        // needed by ormlite
    }

    public Ville(String nom, String codePostal, long pays) {

        this.nom = nom;
        this.codePostal = codePostal;
        this.pays = pays;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("id=").append(this.id);
        sb.append(", ").append("nom : ").append(this.nom);
        sb.append(", ").append("code Postal : ").append(this.codePostal);
        sb.append(", ").append("Pays : ").append(this.pays);


        return sb.toString();
    }
}
